### ISSUE TITLE
Publish job fails if artefacts are not built against Java 1.8

### ISSUE THREAD

**Issue by ljwagerfield** [djspiewak/sbt-github-actions#4] opened 2020-04-25 11:16 UTC
The `publish` job is failing for me if I use anything other than `adopt@1.8` as the Java version for my project.

From the README:

> `githubWorkflowJavaVersions : Seq[String]` – A list of Java versions, using Jabba syntax, which will be used to `build` your project. Note that the `publish` job will always run under solely `adopt@1.8`. Defaults to `adopt@1.8`.

Because my project requires `Java 11`, I have specified this via:

```scala
ThisBuild / githubWorkflowJavaVersions := Seq("11")
```

But this results in the `publish` job failing, since it assumes artefacts are always published under `adopt@1.8`.

Either both need to be fixed to `adopt@1.8` or both need to be configurable (preferred), no?

Uploads with `Java 11`:

![image](https://user-images.githubusercontent.com/3638917/80278436-115f0600-86ee-11ea-9657-5e393ce6fc4c.png)

Downloads with `Java 1.8` (and obviously fails in doing so):

![image](https://user-images.githubusercontent.com/3638917/80278449-33588880-86ee-11ea-9e3a-87a74ec3b911.png)

**Comment by ya-goodfella** [comment] 2020-04-29 20:08
One of my projects just can't be built without Java 14 since it uses JEP-370 API.

@djspiewak can you please explain the point of pinning of `publish` job to `adopt@1.8`? I just can't figure it out, seems like I'm missing something.

**Comment by djspiewak** [comment] 2020-04-29 20:17
There probably isn't a good reason for it. :-) I think the right thing to do is probably pin the publish job to the head of the JVMs list. I'll PR that quickly.

**Comment by djspiewak** [comment] 2020-04-29 20:33
Fixed in 0.6.2!

**Closed by djspiewak** 2020-04-29 20:33 UTC

**Comment by ljwagerfield** [comment] 2020-04-30 07:54
> There probably isn't a good reason for it. :-) I think the right thing to do is probably pin the publish job to the head of the JVMs list. I'll PR that quickly.

But won't the download step fail if the publish job doesn't use the exact same version as the build job?

As per my screenshots, the publish job and the build job use the java version for the URLs they fetch/save assets to (respectively), thus if they differ, the publish job will fail.

> the right thing to do is probably pin the publish job to the head of the JVMs list

Isn't the right thing to make the publish job use the same version as the build job instead?

**Comment by djspiewak** [comment] 2020-04-30 15:49
> Isn't the right thing to make the publish job use the same version as the build job instead?

Well, the problem is that you can build with *multiple* JVMs (easy example: JDK 8 and JDK 11, but Graal also qualifies). You only want the publish job to run once, so we have to pick a JVM to use. The good news is that, as long as all of the build JVMs uploaded their artifacts, the publish job can use any one of them and it's fine. The only exception would be if you build different artifacts on different JVM versions and need them all to publish under some sort of version classifier scheme. I'm not aware of anyone who is actually doing something like that though (it would be really hard to correctly *resolve* such artifacts in downstream projects), so I feel pretty comfy declaring it "out of scope". :-)
